### ISSUE TITLE
Database Initialisation

### ISSUE THREAD

**Issue by harneyp2** [harneyp2/bikemap#2]
The longitude and latitude values are swapped as they are stored in the database. The columns in the SQLite DB need to be renamed to reflect this.

**Comment by DevCarl** [comment]
Fixed the issue. Updated Database_Fixer.py which will create a new table, swap the values into the new table and drop the old one. It will be run once, and should not take any time considering this is the static table rather than dynamic.
Code has also been swapped in core.py which swaps the two values in the table creation if being run for the first time.
